spring:
  application:
    name: CalculadoraUcelo
  datasource:
    # define endereco do banco de dados
    url: jdbc:mysql://localhost:3306/ucelo?useSSL=false&serverTimezone=UTC
    # usuario do Banco de Dados
    username: root
    # senha do banco
    password: Senai@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
